name: Auto Update Data

on:
  schedule:
    - cron: '0 21 * * *'  # 毎日21:00 JST
  workflow_dispatch:

permissions:            # ← この行を追加
  contents: write       # ← これでpush許可

jobs:
  update-data:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          mkdir -p data
          python scraper.py

      - name: Commit and push changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git status
          git add data/latest_data.csv
          git commit -m "Auto-update latest_data.csv" || echo "No changes to commit"
          git push
        continue-on-error: true
